services:
  ChainlitYY:
    image: "zinohome/chainlityy:v0.0.1"
    container_name: ChainlitYY
    hostname: ChainlitYY
    restart: unless-stopped
    ports:
      - "8000:8000/tcp"
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true